# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-05 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
